services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
    networks:
      - mqttnet
    command: mosquitto -c /mosquitto.conf
    volumes:
      - ./mosquitto.conf:/mosquitto.conf
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-h", "localhost", "-t", "test"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  mqttnet:
