log_type all # Logs all types of messages (errors, warnings, information, debug).
log_dest stdout # So you see logs with docker logs mosquitto
listener 1883 # Listen on port 1883
allow_anonymous true # No authentication required during development